/**
 * The service catalogue: every category the app offers, and the sub-types
 * inside each one.
 *
 * Shared by `prisma/seed.ts` (which sets up a fresh development database) and
 * `scripts/backfill-subcategories.ts` (which adds the sub-types to a database
 * whose categories already exist). Kept in one place because two copies of a
 * 26-entry list drift the moment anyone edits only one of them.
 *
 * This is a starting point, not the source of truth — once it is loaded, admins
 * maintain the catalogue from the dashboard, and neither consumer overwrites
 * what they change.
 */
export const SERVICE_CATALOGUE = [
  {
    name: "Plumber",
    slug: "plumber",
    icon: "🔧",
    displayOrder: 1,
    description: "Pipe repair, faucet installation, water heater services",
    subcategories: [
      "Leak repair",
      "Faucet & tap fitting",
      "Drain unclogging",
      "Water heater (geyser) service",
      "Bathroom fittings",
      "Pipe installation",
    ],
  },
  {
    name: "Electrician",
    slug: "electrician",
    icon: "⚡",
    displayOrder: 2,
    description: "Wiring, switchboard installation, electrical repairs",
    subcategories: [
      "Wiring & rewiring",
      "Switchboard & sockets",
      "Fan installation",
      "Light & fixture fitting",
      "Fault finding",
      "Meter & DB board",
    ],
  },
  {
    name: "AC Repair",
    slug: "ac-repair",
    icon: "❄️",
    displayOrder: 3,
    description: "Air conditioner repair and maintenance",
    subcategories: [
      "AC servicing",
      "Gas refill",
      "Cooling issue",
      "AC installation",
      "Uninstall & shifting",
      "PCB & electrical fault",
      "Water leakage",
    ],
  },
  {
    name: "AC Jet Washing",
    slug: "ac-jet-washing",
    icon: "💨",
    displayOrder: 4,
    description: "Deep cleaning of AC units using jet wash",
    subcategories: [
      "Split AC jet wash",
      "Window AC jet wash",
      "Cassette & ducted AC wash",
      "Deep chemical wash",
    ],
  },
  {
    name: "Car Wash",
    slug: "car-wash",
    icon: "🚗",
    displayOrder: 5,
    description: "Car cleaning, detailing, and washing services",
    subcategories: [
      "Exterior wash",
      "Interior vacuum & shampoo",
      "Full detailing",
      "Waxing & polishing",
      "Engine bay cleaning",
    ],
  },
  {
    name: "Solar Installation",
    slug: "solar-installation",
    icon: "☀️",
    displayOrder: 6,
    description: "Solar panel system installation and setup",
    subcategories: [
      "On-grid system",
      "Off-grid system",
      "Hybrid system",
      "Net metering setup",
      "Inverter installation",
      "Structure & mounting",
    ],
  },
  {
    name: "Solar Panel Wash",
    slug: "solar-panel-wash",
    icon: "🧹",
    displayOrder: 7,
    description: "Cleaning and maintenance of solar panels",
    subcategories: [
      "Rooftop panel cleaning",
      "Ground-mount cleaning",
      "Performance & maintenance check",
    ],
  },
  {
    name: "Car Tow & Chain",
    slug: "car-tow-chain",
    icon: "🛞",
    displayOrder: 8,
    description: "Vehicle towing and recovery services",
    subcategories: [
      "Flatbed towing",
      "Chain & hook towing",
      "Jump start",
      "Fuel delivery",
      "Accident recovery",
    ],
  },
  {
    name: "Vehicle Mechanic",
    slug: "vehicle-mechanic",
    icon: "🔩",
    displayOrder: 9,
    description: "Car, bike, and vehicle repair services",
    subcategories: [
      "Car repair",
      "Bike repair",
      "Engine tuning",
      "Brake & suspension",
      "Oil & filter change",
      "Vehicle AC repair",
      "Electrical fault",
    ],
  },
  {
    name: "Puncture Wala",
    slug: "puncture-wala",
    icon: "🛞",
    displayOrder: 10,
    description: "Tire puncture repair and inflation services",
    subcategories: [
      "Tyre puncture repair",
      "Tubeless tyre repair",
      "Air filling & pressure check",
      "Tyre replacement",
      "Wheel balancing",
    ],
  },
  {
    name: "Home Painter",
    slug: "home-painter",
    icon: "🎨",
    displayOrder: 11,
    description: "Interior and exterior painting services",
    subcategories: [
      "Interior painting",
      "Exterior painting",
      "Wall putty & primer",
      "Wood polish",
      "Waterproofing",
    ],
  },
  {
    name: "House Cleaner",
    slug: "house-cleaner",
    icon: "🧹",
    displayOrder: 12,
    description: "Home cleaning, deep cleaning, and sanitization",
    subcategories: [
      "General cleaning",
      "Deep cleaning",
      "Kitchen cleaning",
      "Bathroom cleaning",
      "Sofa & carpet shampoo",
      "Post-construction cleaning",
    ],
  },
  {
    name: "Gardener",
    slug: "gardener",
    icon: "🌿",
    displayOrder: 13,
    description: "Lawn care, gardening, and plant maintenance",
    subcategories: [
      "Lawn mowing",
      "Plant care & pruning",
      "Garden setup",
      "Tree trimming",
      "Irrigation & sprinklers",
    ],
  },
  {
    name: "Mason",
    slug: "mason",
    icon: "🧱",
    displayOrder: 14,
    description: "Brickwork, plastering, and construction services",
    subcategories: [
      "Brickwork",
      "Plastering",
      "Tile & marble fixing",
      "Concrete work",
      "Repair & patchwork",
    ],
  },
  {
    name: "Welder & Iron Worker",
    slug: "welder-iron-worker",
    icon: "⚙️",
    displayOrder: 15,
    description: "Welding, gate making, and iron fabrication",
    subcategories: [
      "Gate & grill making",
      "Railing & stairs",
      "Window & door frames",
      "Welding repair",
      "Shed & canopy",
    ],
  },
  {
    name: "Key & Lock Maker",
    slug: "key-lock-maker",
    icon: "🔑",
    displayOrder: 16,
    description: "Lock installation, repair, and key duplication",
    subcategories: [
      "Key duplication",
      "Lock installation",
      "Lock repair",
      "Emergency unlocking",
      "Digital & smart locks",
    ],
  },
  {
    name: "Pest Control",
    slug: "pest-control",
    icon: "🐜",
    displayOrder: 17,
    description: "Pest extermination and prevention services",
    subcategories: [
      "Cockroach control",
      "Termite treatment",
      "Rodent control",
      "Mosquito & fly control",
      "Bed bug treatment",
      "General fumigation",
    ],
  },
  {
    name: "Water Tank Cleaning",
    slug: "water-tank-cleaning",
    icon: "💧",
    displayOrder: 18,
    description: "Overhead and underground water tank cleaning",
    subcategories: [
      "Overhead tank cleaning",
      "Underground tank cleaning",
      "Disinfection & sanitisation",
      "Leak sealing",
    ],
  },
  {
    name: "Water Bore & Pump",
    slug: "water-bore-pump",
    icon: "🪣",
    displayOrder: 19,
    description: "Boring, pump installation, and repair services",
    subcategories: [
      "Borehole drilling",
      "Pump installation",
      "Pump repair",
      "Motor rewinding",
      "Pipeline work",
    ],
  },
  {
    name: "UPS & Battery Fix",
    slug: "ups-battery-fix",
    icon: "🔋",
    displayOrder: 20,
    description: "UPS repair, battery replacement, and maintenance",
    subcategories: [
      "UPS repair",
      "Battery replacement",
      "Battery maintenance",
      "Inverter installation",
      "Wiring & load setup",
    ],
  },
  {
    name: "Fridge / Washing Machine Repair",
    slug: "fridge-washing-machine-repair",
    icon: "🧊",
    displayOrder: 21,
    description: "Refrigerator and washing machine repair",
    subcategories: [
      "Refrigerator repair",
      "Deep freezer repair",
      "Washing machine repair",
      "Dryer repair",
      "Fridge gas refill",
      "Microwave & oven repair",
    ],
  },
  {
    name: "Load & Unload",
    slug: "load-unload",
    icon: "📦",
    displayOrder: 22,
    description: "Loading, unloading, and moving services",
    subcategories: [
      "House shifting",
      "Office shifting",
      "Furniture moving",
      "Labour only",
      "Packing service",
    ],
  },
  {
    name: "Scrap Buyer",
    slug: "scrap-buyer",
    icon: "♻️",
    displayOrder: 23,
    description: "Old scrap, metal, and item buying services",
    subcategories: [
      "Metal & iron scrap",
      "Electronics & appliances",
      "Paper & cardboard",
      "Plastic scrap",
      "Vehicle scrap",
    ],
  },
  {
    name: "Carpenter",
    slug: "carpenter",
    icon: "🪚",
    displayOrder: 24,
    description: "Furniture making, repair, and woodwork",
    subcategories: [
      "Furniture making",
      "Furniture repair",
      "Door & window work",
      "Kitchen cabinets",
      "Wardrobe & storage",
      "Ceiling & panelling",
    ],
  },
  {
    name: "Generator Mechanic",
    slug: "generator-mechanic",
    icon: "🔌",
    displayOrder: 25,
    description: "Generator repair, maintenance, and servicing",
    subcategories: [
      "Generator servicing",
      "Generator repair",
      "Generator installation",
      "Auto-start (ATS) setup",
      "Oil & filter change",
    ],
  },
  {
    name: "Hair Dresser at Home",
    slug: "hair-dresser-at-home",
    icon: "💇",
    displayOrder: 26,
    description: "Professional hair dressing and styling at home",
    subcategories: [
      "Men's haircut",
      "Women's haircut",
      "Hair colouring",
      "Hair treatment",
      "Bridal styling",
      "Shave & grooming",
    ],
  },
];

export type ServiceCatalogueEntry = (typeof SERVICE_CATALOGUE)[number];
